### PR TITLE
Upgrade to Quarkus 3

### PR DESCRIPTION
**Pull request by gsmet**
@Sgitario I tried to update to Quarkus 3 but tests are failing with:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.0.Final:build (default) on project quarkus-certmanager-integration-tests-openshift-certmanager-ssl: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.RuntimeException: Cycle detected when ordering decorators: 
[ERROR] - io.dekorate.openshift.decorator.ApplyDeploymentTriggerDecorator
[ERROR] - io.dekorate.s2i.decorator.AddBuildConfigResourceDecorator
[ERROR] - io.quarkus.kubernetes.deployment.ApplyBuilderImageDecorator
[ERROR] - io.quarkus.kubernetes.deployment.ApplyContainerImageDecorator
[ERROR] - io.quarkus.kubernetes.deployment.ApplyHttpGetActionPortDecorator
[ERROR] - io.quarkus.kubernetes.deployment.ApplyServiceTypeDecorator
[ERROR] - io.quarkus.kubernetes.deployment.RemoveBuilderImageResourceDecorator
[ERROR] - io.dekorate.certmanager.decorator.AddCertificateResourceDecorator
[ERROR] - io.dekorate.certmanager.decorator.AddSelfSignedIssuerResourceDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddAnnotationDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddCommitIdAnnotationDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddEnvVarDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddLabelDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddMetadataToTemplateDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddMountDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddPortDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddSecretVolumeDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddSelectorToDeploymentSpecDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddToSelectorDecorator
[ERROR] - io.dekorate.kubernetes.decorator.AddVcsUrlAnnotationDecorator
[ERROR] - io.dekorate.kubernetes.decorator.ApplyImagePullPolicyDecorator
[ERROR] - io.dekorate.kubernetes.decorator.RemoveAnnotationDecorator
[ERROR] - io.dekorate.kubernetes.decorator.RemoveProbesFromInitContainerDecorator
[ERROR] 
[ERROR] 	at io.dekorate.utils.TopologicalSort.throwCycleDetectedException(TopologicalSort.java:168)
[ERROR] 	at io.dekorate.utils.TopologicalSort.sortNodes(TopologicalSort.java:134)
[ERROR] 	at io.dekorate.utils.TopologicalSort.sortDecorators(TopologicalSort.java:37)
[ERROR] 	at io.dekorate.ResourceRegistry.lambda$generate$2(ResourceRegistry.java:179)
[ERROR] 	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
[ERROR] 	at io.dekorate.ResourceRegistry.generate(ResourceRegistry.java:173)
[ERROR] 	at io.dekorate.Session.generate(Session.java:293)
[ERROR] 	at io.dekorate.Session.close(Session.java:256)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$3(KubernetesProcessor.java:194)

```

Probably worth a look. When you're done with this, could you release a new major and ping me with the version number?

Thanks.

### CODE REVIEW

**Comment by Sgitario** [comment]
> @Sgitario I tried to update to Quarkus 3 but tests are failing with:
> 
> ```
> [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.0.Final:build (default) on project quarkus-certmanager-integration-tests-openshift-certmanager-ssl: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> [ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.RuntimeException: Cycle detected when ordering decorators: 
> [ERROR] - io.dekorate.openshift.decorator.ApplyDeploymentTriggerDecorator
> [ERROR] - io.dekorate.s2i.decorator.AddBuildConfigResourceDecorator
> [ERROR] - io.quarkus.kubernetes.deployment.ApplyBuilderImageDecorator
> [ERROR] - io.quarkus.kubernetes.deployment.ApplyContainerImageDecorator
> [ERROR] - io.quarkus.kubernetes.deployment.ApplyHttpGetActionPortDecorator
> [ERROR] - io.quarkus.kubernetes.deployment.ApplyServiceTypeDecorator
> [ERROR] - io.quarkus.kubernetes.deployment.RemoveBuilderImageResourceDecorator
> [ERROR] - io.dekorate.certmanager.decorator.AddCertificateResourceDecorator
> [ERROR] - io.dekorate.certmanager.decorator.AddSelfSignedIssuerResourceDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddAnnotationDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddCommitIdAnnotationDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddEnvVarDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddLabelDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddMetadataToTemplateDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddMountDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddPortDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddSecretVolumeDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddSelectorToDeploymentSpecDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddToSelectorDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.AddVcsUrlAnnotationDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.ApplyImagePullPolicyDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.RemoveAnnotationDecorator
> [ERROR] - io.dekorate.kubernetes.decorator.RemoveProbesFromInitContainerDecorator
> [ERROR] 
> [ERROR] 	at io.dekorate.utils.TopologicalSort.throwCycleDetectedException(TopologicalSort.java:168)
> [ERROR] 	at io.dekorate.utils.TopologicalSort.sortNodes(TopologicalSort.java:134)
> [ERROR] 	at io.dekorate.utils.TopologicalSort.sortDecorators(TopologicalSort.java:37)
> [ERROR] 	at io.dekorate.ResourceRegistry.lambda$generate$2(ResourceRegistry.java:179)
> [ERROR] 	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
> [ERROR] 	at io.dekorate.ResourceRegistry.generate(ResourceRegistry.java:173)
> [ERROR] 	at io.dekorate.Session.generate(Session.java:293)
> [ERROR] 	at io.dekorate.Session.close(Session.java:256)
> [ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$3(KubernetesProcessor.java:194)
> ```
> 
> Probably worth a look. When you're done with this, could you release a new major and ping me with the version number?
> 
> Thanks.

Sure

**Comment by Sgitario** [comment]
This issue needs to be fixed in Dekorate first: https://github.com/dekorateio/dekorate/pull/1189
The good thing is that we don't need to wait for Quarkus to bump Dekorate to the Dekorate new release, will use the new release directly in this extension.

**Comment by gsmet** [comment]
Given we enforce the version with the BOM, it will fail anyway though, won't it? In that case, better wait for the update in Quarkus.

**Comment by Sgitario** [comment]
> Given we enforce the version with the BOM, it will fail anyway though, won't it? In that case, better wait for the update in Quarkus.

The BOM uses `certmanager-annotations` with the `no-apt` classifier. If we use the normal dependency, it works fine. This way we don't need to wait for Quarkus 3.1 and can provide a working release for Quarkus 3.0.

**Comment by Sgitario** [comment]
Superseded by https://github.com/quarkiverse/quarkus-cert-manager/pull/40

**Comment by Sgitario** [comment]
@gsmet Version 1.0.0: https://github.com/quarkiverse/quarkus-cert-manager/releases/tag/1.0.0

**Pull request closed without merging**
